name: Test Pull Request Builds

on:
  push:
    # branches: master
  pull_request:
    # branches: master
  
jobs:
  cache-directories:
    runs-on: ubuntu-latest
    steps:
    - name: Cache multiple directories
      uses: actions/cache@v2
      with:
        path: [
          bld_external/blahp-1.16.5.1-p26,
          bld_external/boinc-client_release-7.14-7.14.1,
          bld_external/boost-1.66.0-p1,
          bld_external/canl-c-2.1.6,
          bld_external/drmaa-1.6.2-p1,
          bld_external/glibc-2.17-157-x86_64,
          bld_external/glite-ce-cream-client-api-c-1.15.4-p1,
          bld_external/glite-ce-wsdl-1.15.1,
          bld_external/glite-lbjp-common-gsoap-plugin-3.2.12,
          bld_external/glite-lbjp-common-gss-3.2.16,
          bld_external/globus-6.0-p2,
          bld_external/gridsite-2.2.6,
          bld_external/gsoap_2.7.16-p1,
          bld_external/log4cpp-1.0-3,
          bld_external/libcgroup-0.41,
          bld_external/munge-0.5.13,
          bld_external/unicoregahp-1.2.0,
          bld_external/voms-2.1.0-rc0,
          bld_external/zlib-1.2.3,
          bld_external_rhel/blahp-1.16.5.1-p26,
          bld_external_rhel/boinc-client_release-7.14-7.14.1,
          bld_external_rhel/boost-1.66.0-p1,
          bld_external_rhel/canl-c-2.1.6,
          bld_external_rhel/drmaa-1.6.2-p1,
          bld_external_rhel/glibc-2.17-157-x86_64,
          bld_external_rhel/glite-ce-cream-client-api-c-1.15.4-p1,
          bld_external_rhel/glite-ce-wsdl-1.15.1,
          bld_external_rhel/glite-lbjp-common-gsoap-plugin-3.2.12,
          bld_external_rhel/glite-lbjp-common-gss-3.2.16,
          bld_external_rhel/globus-6.0-p2,
          bld_external_rhel/gridsite-2.2.6,
          bld_external_rhel/gsoap_2.7.16-p1,
          bld_external_rhel/log4cpp-1.0-3,
          bld_external_rhel/libcgroup-0.41,
          bld_external_rhel/munge-0.5.13,
          bld_external_rhel/unicoregahp-1.2.0,
          bld_external_rhel/voms-2.1.0-rc0,
          bld_external_rhel/zlib-1.2.3,
        ]

  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: MacOS build with UW_BUILD
      env:
        UW_BUILD: ON
        PROPER: OFF
        VOMS: ON
        GLOBUS: ON
        SCITOKENS: OFF
      run: |
        sudo mkdir -p /etc/default && sudo touch /etc/default/docker
        echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null

    - name: MacOS build without UW_BUILD
      env:
        UW_BUILD: OFF
        PROPER: ON
        VOMS: OFF
        GLOBUS: OFF
        SCITOKENS: OFF
      run: |
        sudo mkdir -p /etc/default && sudo touch /etc/default/docker
        echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Linux build CI with UW_BUILD
      env:
        UW_BUILD: ON
        PROPER: OFF
        VOMS: ON
        GLOBUS: ON
        SCITOKENS: ON
      run: |
        sudo apt-get install -y --no-install-recommends  \
          chrpath cmake default-jdk gfortran globus-core help2man \
          libboost-filesystem-dev libboost-program-options-dev  \
          libboost-python-dev libboost-regex-dev libboost-system-dev  \
          libboost-test-dev libboost-thread-dev libcgroup-dev  \
          libcurl4-openssl-dev libglobus-common-dev libglobus-ftp-client-dev  \
          libglobus-gass-server-ez-dev libglobus-gram-client-dev  \
          libglobus-gram-protocol-dev libglobus-gss-assist-dev libmunge-dev  \
          libpq-dev libvirt-dev libxml2-dev po-debconf \
          libc-ares-dev voms-dev libtool-bin uuid-dev

    - name: Linux build CI without UW_BUILD
      env:
        UW_BUILD: OFF
        PROPER: ON
        VOMS: ON
        GLOBUS: ON
        SCITOKENS: OFF
      run: |
        sudo apt-get install -y --no-install-recommends  \
          chrpath cmake default-jdk gfortran globus-core help2man \
          libboost-filesystem-dev libboost-program-options-dev  \
          libboost-python-dev libboost-regex-dev libboost-system-dev  \
          libboost-test-dev libboost-thread-dev libcgroup-dev  \
          libcurl4-openssl-dev libglobus-common-dev libglobus-ftp-client-dev  \
          libglobus-gass-server-ez-dev libglobus-gram-client-dev  \
          libglobus-gram-protocol-dev libglobus-gss-assist-dev libmunge-dev  \
          libpq-dev libvirt-dev libxml2-dev po-debconf \
          libc-ares-dev voms-dev libtool-bin uuid-dev

    - name: CentOS 7 build CI
      env:
        UW_BUILD: ON
        PROPER: OFF
        VOMS: ON
        GLOBUS: ON
        SCITOKENS: ON
        DOCKER_IMAGE: centos:centos7
      run: |
        PLATFORM=centos7
        docker pull htcondor/build-$PLATFORM
        docker run --name $GITHUB_SHA --rm --mount type=bind,source="$PWD",target=/home/build/htcondor,readonly htcondor/build-$PLATFORM
        docker exec $GITHUB_SHA /bin/bash